Ingredient.create(name: "lemon")
Ingredient.create(name: "mint")
Ingredient.create(name: "rum")
Ingredient.create(name: "gin")
Ingredient.create(name: "prosecco")
Ingredient.create(name: "coke")
Ingredient.create(name: "tonic")

Cocktail.create(name: "Mojito")
Cocktail.create(name: "Gin & Tonic")
